/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminUserRecord {
  'principal' : Principal,
  'profile' : UserProfile,
}
export interface AppSettings {
  'deliveryCharge' : number,
  'taxEnabled' : boolean,
  'gstNumber' : string,
  'businessName' : string,
  'businessAddress' : string,
  'whatsappNumber' : string,
  'freeDeliveryAbove' : number,
  'servicePincodes' : Array<string>,
  'taxPercentage' : number,
}
export interface Coupon {
  'id' : bigint,
  'active' : boolean,
  'discountValue' : number,
  'expiryDate' : bigint,
  'code' : string,
  'discountType' : CouponDiscountType,
  'usedCount' : bigint,
  'usageLimit' : bigint,
}
export type CouponDiscountType = { 'fixed' : null } |
  { 'percentage' : null };
export interface DashboardStats {
  'totalRevenue' : number,
  'totalCustomers' : bigint,
  'activeSubscriptions' : bigint,
  'todayOrders' : bigint,
}
export interface DeliveryRider {
  'id' : bigint,
  'name' : string,
  'available' : boolean,
  'phone' : string,
}
export interface IngredientItem {
  'id' : bigint,
  'lowStockThreshold' : bigint,
  'name' : string,
  'unit' : string,
  'pricePerUnit' : number,
  'quantity' : bigint,
}
export interface MenuItem {
  'id' : bigint,
  'calories' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : [] | [string],
  'category' : string,
  'price' : number,
  'protein' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'userId' : Principal,
  'createdAt' : bigint,
  'totalAmount' : number,
  'notes' : [] | [string],
  'items' : Array<OrderItem>,
}
export interface OrderDelivery {
  'assignedAt' : [] | [bigint],
  'riderId' : [] | [bigint],
  'deliveryStatus' : [] | [string],
  'orderId' : bigint,
  'riderName' : [] | [string],
}
export interface OrderItem {
  'quantity' : bigint,
  'unitPrice' : number,
  'menuItemId' : bigint,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'outForDelivery' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface SaladIngredient {
  'quantityRequired' : bigint,
  'ingredientId' : bigint,
  'saladId' : bigint,
}
export interface Subscription {
  'id' : bigint,
  'status' : SubscriptionStatus,
  'endDate' : bigint,
  'userId' : Principal,
  'plan' : SubscriptionPlan,
  'remainingSalads' : bigint,
  'totalSalads' : bigint,
  'startDate' : bigint,
}
export type SubscriptionPlan = { 'monthly' : null } |
  { 'weekly' : null };
export type SubscriptionStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'paused' : null };
export interface UserProfile {
  'age' : [] | [bigint],
  'bmi' : [] | [number],
  'weight' : [] | [number],
  'height' : [] | [number],
  'dietaryPreferences' : [] | [string],
  'name' : string,
  'mobileNumber' : string,
  'email' : [] | [string],
  'dietaryRestrictions' : [] | [string],
  'address' : [] | [string],
  'idealWeight' : [] | [number],
  'gender' : [] | [string],
  'dailyCalories' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCoupon' : ActorMethod<[Coupon], undefined>,
  'addDeliveryRider' : ActorMethod<[DeliveryRider], undefined>,
  'addIngredient' : ActorMethod<[IngredientItem], undefined>,
  'addMenuItem' : ActorMethod<[MenuItem], undefined>,
  'adminCancelSubscription' : ActorMethod<[bigint], undefined>,
  'adminCreateSubscription' : ActorMethod<
    [
      Principal,
      SubscriptionPlan,
      bigint,
      bigint,
      bigint,
      bigint,
      SubscriptionStatus,
    ],
    bigint
  >,
  'adminCreateUser' : ActorMethod<[Principal, UserProfile], undefined>,
  'adminDeleteSubscription' : ActorMethod<[bigint], undefined>,
  'adminDeleteUser' : ActorMethod<[Principal], undefined>,
  'adminExtendSubscription' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'adminGetAllUsers' : ActorMethod<[], Array<AdminUserRecord>>,
  'adminPauseSubscription' : ActorMethod<[bigint], undefined>,
  'adminUpdateSubscription' : ActorMethod<
    [
      bigint,
      SubscriptionPlan,
      bigint,
      bigint,
      bigint,
      bigint,
      SubscriptionStatus,
    ],
    undefined
  >,
  'adminUpdateUser' : ActorMethod<[Principal, UserProfile], undefined>,
  'applyCoupon' : ActorMethod<[string], number>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRiderToOrder' : ActorMethod<[bigint, bigint], undefined>,
  'cancelSubscription' : ActorMethod<[], undefined>,
  'createOrUpdateProfile' : ActorMethod<[UserProfile], undefined>,
  'deleteCoupon' : ActorMethod<[bigint], undefined>,
  'deleteIngredient' : ActorMethod<[bigint], undefined>,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'getActiveCoupons' : ActorMethod<[], Array<Coupon>>,
  'getAllCoupons' : ActorMethod<[], Array<Coupon>>,
  'getAllDeliveryRiders' : ActorMethod<[], Array<DeliveryRider>>,
  'getAllIngredients' : ActorMethod<[], Array<IngredientItem>>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllOrderDeliveries' : ActorMethod<[], Array<OrderDelivery>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllSaladIngredients' : ActorMethod<
    [],
    Array<{ 'saladId' : bigint, 'ingredients' : Array<SaladIngredient> }>
  >,
  'getAllSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getAppSettings' : ActorMethod<[], AppSettings>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMenuItemById' : ActorMethod<[bigint], [] | [MenuItem]>,
  'getMenuItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMySubscription' : ActorMethod<[], [] | [Subscription]>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getOrderDelivery' : ActorMethod<[bigint], [] | [OrderDelivery]>,
  'getSaladIngredients' : ActorMethod<[bigint], Array<SaladIngredient>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[Array<OrderItem>, number, [] | [string]], bigint>,
  'saveAppSettings' : ActorMethod<[AppSettings], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSaladIngredients' : ActorMethod<
    [bigint, Array<SaladIngredient>],
    undefined
  >,
  'subscribeToPlan' : ActorMethod<[SubscriptionPlan], bigint>,
  'toggleAvailability' : ActorMethod<[bigint], undefined>,
  'updateCoupon' : ActorMethod<[Coupon], undefined>,
  'updateDeliveryRider' : ActorMethod<[DeliveryRider], undefined>,
  'updateDeliveryStatus' : ActorMethod<[bigint, string], undefined>,
  'updateIngredient' : ActorMethod<[IngredientItem], undefined>,
  'updateMenuItem' : ActorMethod<[MenuItem], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];