/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CouponDiscountType = IDL.Variant({
  'fixed' : IDL.Null,
  'percentage' : IDL.Null,
});
export const Coupon = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'discountValue' : IDL.Float64,
  'expiryDate' : IDL.Int,
  'code' : IDL.Text,
  'discountType' : CouponDiscountType,
  'usedCount' : IDL.Nat,
  'usageLimit' : IDL.Nat,
});
export const DeliveryRider = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'available' : IDL.Bool,
  'phone' : IDL.Text,
});
export const IngredientItem = IDL.Record({
  'id' : IDL.Nat,
  'lowStockThreshold' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'pricePerUnit' : IDL.Float64,
  'quantity' : IDL.Nat,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'price' : IDL.Float64,
  'protein' : IDL.Nat,
});
export const SubscriptionPlan = IDL.Variant({
  'monthly' : IDL.Null,
  'weekly' : IDL.Null,
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'paused' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'bmi' : IDL.Float64,
  'weight' : IDL.Float64,
  'height' : IDL.Float64,
  'calorieTarget' : IDL.Opt(IDL.Nat),
  'dietaryPreferences' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'dietaryRestrictions' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'gender' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const AdminUserRecord = IDL.Record({
  'principal' : IDL.Principal,
  'profile' : UserProfile,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderDelivery = IDL.Record({
  'assignedAt' : IDL.Opt(IDL.Int),
  'riderId' : IDL.Opt(IDL.Nat),
  'orderId' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'menuItemId' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Float64,
  'notes' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(OrderItem),
});
export const SaladIngredient = IDL.Record({
  'quantityRequired' : IDL.Nat,
  'ingredientId' : IDL.Nat,
  'saladId' : IDL.Nat,
});
export const Subscription = IDL.Record({
  'id' : IDL.Nat,
  'status' : SubscriptionStatus,
  'endDate' : IDL.Int,
  'userId' : IDL.Principal,
  'plan' : SubscriptionPlan,
  'remainingSalads' : IDL.Nat,
  'totalSalads' : IDL.Nat,
  'startDate' : IDL.Int,
});
export const DashboardStats = IDL.Record({
  'totalRevenue' : IDL.Float64,
  'totalCustomers' : IDL.Nat,
  'activeSubscriptions' : IDL.Nat,
  'todayOrders' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCoupon' : IDL.Func([Coupon], [], []),
  'addDeliveryRider' : IDL.Func([DeliveryRider], [], []),
  'addIngredient' : IDL.Func([IngredientItem], [], []),
  'addMenuItem' : IDL.Func([MenuItem], [], []),
  'adminCancelSubscription' : IDL.Func([IDL.Nat], [], []),
  'adminCreateSubscription' : IDL.Func(
      [
        IDL.Principal,
        SubscriptionPlan,
        IDL.Nat,
        IDL.Nat,
        IDL.Int,
        IDL.Int,
        SubscriptionStatus,
      ],
      [IDL.Nat],
      [],
    ),
  'adminCreateUser' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'adminDeleteSubscription' : IDL.Func([IDL.Nat], [], []),
  'adminDeleteUser' : IDL.Func([IDL.Principal], [], []),
  'adminExtendSubscription' : IDL.Func([IDL.Nat, IDL.Int, IDL.Nat], [], []),
  'adminGetAllUsers' : IDL.Func([], [IDL.Vec(AdminUserRecord)], ['query']),
  'adminPauseSubscription' : IDL.Func([IDL.Nat], [], []),
  'adminUpdateSubscription' : IDL.Func(
      [
        IDL.Nat,
        SubscriptionPlan,
        IDL.Nat,
        IDL.Nat,
        IDL.Int,
        IDL.Int,
        SubscriptionStatus,
      ],
      [],
      [],
    ),
  'adminUpdateUser' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'applyCoupon' : IDL.Func([IDL.Text], [IDL.Float64], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRiderToOrder' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'cancelSubscription' : IDL.Func([], [], []),
  'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
  'deleteCoupon' : IDL.Func([IDL.Nat], [], []),
  'deleteIngredient' : IDL.Func([IDL.Nat], [], []),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
  'getActiveCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'getAllCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'getAllDeliveryRiders' : IDL.Func([], [IDL.Vec(DeliveryRider)], ['query']),
  'getAllIngredients' : IDL.Func([], [IDL.Vec(IngredientItem)], ['query']),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllOrderDeliveries' : IDL.Func([], [IDL.Vec(OrderDelivery)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllSaladIngredients' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'saladId' : IDL.Nat,
            'ingredients' : IDL.Vec(SaladIngredient),
          })
        ),
      ],
      ['query'],
    ),
  'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMenuItemById' : IDL.Func([IDL.Nat], [IDL.Opt(MenuItem)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMySubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrderDelivery' : IDL.Func([IDL.Nat], [IDL.Opt(OrderDelivery)], ['query']),
  'getSaladIngredients' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SaladIngredient)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Vec(OrderItem), IDL.Float64, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSaladIngredients' : IDL.Func([IDL.Nat, IDL.Vec(SaladIngredient)], [], []),
  'subscribeToPlan' : IDL.Func([SubscriptionPlan], [IDL.Nat], []),
  'toggleAvailability' : IDL.Func([IDL.Nat], [], []),
  'updateCoupon' : IDL.Func([Coupon], [], []),
  'updateDeliveryRider' : IDL.Func([DeliveryRider], [], []),
  'updateIngredient' : IDL.Func([IngredientItem], [], []),
  'updateMenuItem' : IDL.Func([MenuItem], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CouponDiscountType = IDL.Variant({
    'fixed' : IDL.Null,
    'percentage' : IDL.Null,
  });
  const Coupon = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'discountValue' : IDL.Float64,
    'expiryDate' : IDL.Int,
    'code' : IDL.Text,
    'discountType' : CouponDiscountType,
    'usedCount' : IDL.Nat,
    'usageLimit' : IDL.Nat,
  });
  const DeliveryRider = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const IngredientItem = IDL.Record({
    'id' : IDL.Nat,
    'lowStockThreshold' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'pricePerUnit' : IDL.Float64,
    'quantity' : IDL.Nat,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'price' : IDL.Float64,
    'protein' : IDL.Nat,
  });
  const SubscriptionPlan = IDL.Variant({
    'monthly' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'paused' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'bmi' : IDL.Float64,
    'weight' : IDL.Float64,
    'height' : IDL.Float64,
    'calorieTarget' : IDL.Opt(IDL.Nat),
    'dietaryPreferences' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'dietaryRestrictions' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'gender' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const AdminUserRecord = IDL.Record({
    'principal' : IDL.Principal,
    'profile' : UserProfile,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderDelivery = IDL.Record({
    'assignedAt' : IDL.Opt(IDL.Int),
    'riderId' : IDL.Opt(IDL.Nat),
    'orderId' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'menuItemId' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Float64,
    'notes' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(OrderItem),
  });
  const SaladIngredient = IDL.Record({
    'quantityRequired' : IDL.Nat,
    'ingredientId' : IDL.Nat,
    'saladId' : IDL.Nat,
  });
  const Subscription = IDL.Record({
    'id' : IDL.Nat,
    'status' : SubscriptionStatus,
    'endDate' : IDL.Int,
    'userId' : IDL.Principal,
    'plan' : SubscriptionPlan,
    'remainingSalads' : IDL.Nat,
    'totalSalads' : IDL.Nat,
    'startDate' : IDL.Int,
  });
  const DashboardStats = IDL.Record({
    'totalRevenue' : IDL.Float64,
    'totalCustomers' : IDL.Nat,
    'activeSubscriptions' : IDL.Nat,
    'todayOrders' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCoupon' : IDL.Func([Coupon], [], []),
    'addDeliveryRider' : IDL.Func([DeliveryRider], [], []),
    'addIngredient' : IDL.Func([IngredientItem], [], []),
    'addMenuItem' : IDL.Func([MenuItem], [], []),
    'adminCancelSubscription' : IDL.Func([IDL.Nat], [], []),
    'adminCreateSubscription' : IDL.Func(
        [
          IDL.Principal,
          SubscriptionPlan,
          IDL.Nat,
          IDL.Nat,
          IDL.Int,
          IDL.Int,
          SubscriptionStatus,
        ],
        [IDL.Nat],
        [],
      ),
    'adminCreateUser' : IDL.Func([IDL.Principal, UserProfile], [], []),
    'adminDeleteSubscription' : IDL.Func([IDL.Nat], [], []),
    'adminDeleteUser' : IDL.Func([IDL.Principal], [], []),
    'adminExtendSubscription' : IDL.Func([IDL.Nat, IDL.Int, IDL.Nat], [], []),
    'adminGetAllUsers' : IDL.Func([], [IDL.Vec(AdminUserRecord)], ['query']),
    'adminPauseSubscription' : IDL.Func([IDL.Nat], [], []),
    'adminUpdateSubscription' : IDL.Func(
        [
          IDL.Nat,
          SubscriptionPlan,
          IDL.Nat,
          IDL.Nat,
          IDL.Int,
          IDL.Int,
          SubscriptionStatus,
        ],
        [],
        [],
      ),
    'adminUpdateUser' : IDL.Func([IDL.Principal, UserProfile], [], []),
    'applyCoupon' : IDL.Func([IDL.Text], [IDL.Float64], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRiderToOrder' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'cancelSubscription' : IDL.Func([], [], []),
    'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
    'deleteCoupon' : IDL.Func([IDL.Nat], [], []),
    'deleteIngredient' : IDL.Func([IDL.Nat], [], []),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
    'getActiveCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'getAllCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'getAllDeliveryRiders' : IDL.Func([], [IDL.Vec(DeliveryRider)], ['query']),
    'getAllIngredients' : IDL.Func([], [IDL.Vec(IngredientItem)], ['query']),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllOrderDeliveries' : IDL.Func([], [IDL.Vec(OrderDelivery)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllSaladIngredients' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'saladId' : IDL.Nat,
              'ingredients' : IDL.Vec(SaladIngredient),
            })
          ),
        ],
        ['query'],
      ),
    'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMenuItemById' : IDL.Func([IDL.Nat], [IDL.Opt(MenuItem)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMySubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrderDelivery' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(OrderDelivery)],
        ['query'],
      ),
    'getSaladIngredients' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SaladIngredient)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Vec(OrderItem), IDL.Float64, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSaladIngredients' : IDL.Func(
        [IDL.Nat, IDL.Vec(SaladIngredient)],
        [],
        [],
      ),
    'subscribeToPlan' : IDL.Func([SubscriptionPlan], [IDL.Nat], []),
    'toggleAvailability' : IDL.Func([IDL.Nat], [], []),
    'updateCoupon' : IDL.Func([Coupon], [], []),
    'updateDeliveryRider' : IDL.Func([DeliveryRider], [], []),
    'updateIngredient' : IDL.Func([IngredientItem], [], []),
    'updateMenuItem' : IDL.Func([MenuItem], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };