/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Coupon {
    id: bigint;
    active: boolean;
    discountValue: number;
    expiryDate: bigint;
    code: string;
    discountType: CouponDiscountType;
    usedCount: bigint;
    usageLimit: bigint;
}
export interface OrderItem {
    quantity: bigint;
    unitPrice: number;
    menuItemId: bigint;
}
export interface DashboardStats {
    totalRevenue: number;
    totalCustomers: bigint;
    activeSubscriptions: bigint;
    todayOrders: bigint;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    userId: Principal;
    createdAt: bigint;
    totalAmount: number;
    notes?: string;
    items: Array<OrderItem>;
}
export interface Subscription {
    id: bigint;
    status: SubscriptionStatus;
    userId: Principal;
    plan: SubscriptionPlan;
    startDate: bigint;
}
export interface MenuItem {
    id: bigint;
    calories: bigint;
    name: string;
    description: string;
    available: boolean;
    category: string;
    price: number;
}
export interface OrderDelivery {
    assignedAt?: bigint;
    riderId?: bigint;
    orderId: bigint;
}
export interface DeliveryRider {
    id: bigint;
    name: string;
    available: boolean;
    phone: string;
}
export interface IngredientItem {
    id: bigint;
    lowStockThreshold: bigint;
    name: string;
    unit: string;
    pricePerUnit: number;
    quantity: bigint;
}
export interface UserProfile {
    age: bigint;
    bmi: number;
    weight: number;
    height: number;
    name: string;
    email: string;
}
export enum CouponDiscountType {
    fixed = "fixed",
    percentage = "percentage"
}
export enum OrderStatus {
    preparing = "preparing",
    cancelled = "cancelled",
    pending = "pending",
    outForDelivery = "outForDelivery",
    delivered = "delivered",
    confirmed = "confirmed"
}
export enum SubscriptionPlan {
    monthly = "monthly",
    weekly = "weekly"
}
export enum SubscriptionStatus {
    active = "active",
    cancelled = "cancelled"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCoupon(coupon: Coupon): Promise<void>;
    addDeliveryRider(rider: DeliveryRider): Promise<void>;
    addIngredient(item: IngredientItem): Promise<void>;
    addMenuItem(item: MenuItem): Promise<void>;
    applyCoupon(code: string): Promise<number>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRiderToOrder(orderId: bigint, riderId: bigint): Promise<void>;
    cancelSubscription(): Promise<void>;
    createOrUpdateProfile(profile: UserProfile): Promise<void>;
    deleteCoupon(id: bigint): Promise<void>;
    deleteIngredient(id: bigint): Promise<void>;
    getActiveCoupons(): Promise<Array<Coupon>>;
    getAllCoupons(): Promise<Array<Coupon>>;
    getAllDeliveryRiders(): Promise<Array<DeliveryRider>>;
    getAllIngredients(): Promise<Array<IngredientItem>>;
    getAllMenuItems(): Promise<Array<MenuItem>>;
    getAllOrderDeliveries(): Promise<Array<OrderDelivery>>;
    getAllOrders(): Promise<Array<Order>>;
    getAllSubscriptions(): Promise<Array<Subscription>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getMenuItemById(id: bigint): Promise<MenuItem | null>;
    getMenuItemsByCategory(category: string): Promise<Array<MenuItem>>;
    getMyOrders(): Promise<Array<Order>>;
    getMyProfile(): Promise<UserProfile | null>;
    getMySubscription(): Promise<Subscription | null>;
    getOrderById(orderId: bigint): Promise<Order | null>;
    getOrderDelivery(orderId: bigint): Promise<OrderDelivery | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    placeOrder(items: Array<OrderItem>, totalAmount: number, notes: string | null): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    subscribeToPlan(plan: SubscriptionPlan): Promise<bigint>;
    toggleAvailability(id: bigint): Promise<void>;
    updateCoupon(coupon: Coupon): Promise<void>;
    updateDeliveryRider(rider: DeliveryRider): Promise<void>;
    updateIngredient(item: IngredientItem): Promise<void>;
    updateMenuItem(item: MenuItem): Promise<void>;
    updateOrderStatus(orderId: bigint, status: OrderStatus): Promise<void>;
}
import type { Coupon as _Coupon, CouponDiscountType as _CouponDiscountType, MenuItem as _MenuItem, Order as _Order, OrderDelivery as _OrderDelivery, OrderItem as _OrderItem, OrderStatus as _OrderStatus, Subscription as _Subscription, SubscriptionPlan as _SubscriptionPlan, SubscriptionStatus as _SubscriptionStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCoupon(arg0: Coupon): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoupon(to_candid_Coupon_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoupon(to_candid_Coupon_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addDeliveryRider(arg0: DeliveryRider): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDeliveryRider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDeliveryRider(arg0);
            return result;
        }
    }
    async addIngredient(arg0: IngredientItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addIngredient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIngredient(arg0);
            return result;
        }
    }
    async addMenuItem(arg0: MenuItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(arg0);
            return result;
        }
    }
    async applyCoupon(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.applyCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyCoupon(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRiderToOrder(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRiderToOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRiderToOrder(arg0, arg1);
            return result;
        }
    }
    async cancelSubscription(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelSubscription();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelSubscription();
            return result;
        }
    }
    async createOrUpdateProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(arg0);
            return result;
        }
    }
    async deleteCoupon(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoupon(arg0);
            return result;
        }
    }
    async deleteIngredient(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIngredient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIngredient(arg0);
            return result;
        }
    }
    async getActiveCoupons(): Promise<Array<Coupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveCoupons();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveCoupons();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCoupons(): Promise<Array<Coupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCoupons();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCoupons();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDeliveryRiders(): Promise<Array<DeliveryRider>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeliveryRiders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeliveryRiders();
            return result;
        }
    }
    async getAllIngredients(): Promise<Array<IngredientItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIngredients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIngredients();
            return result;
        }
    }
    async getAllMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMenuItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMenuItems();
            return result;
        }
    }
    async getAllOrderDeliveries(): Promise<Array<OrderDelivery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrderDeliveries();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrderDeliveries();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSubscriptions(): Promise<Array<Subscription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubscriptions();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubscriptions();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getMenuItemById(arg0: bigint): Promise<MenuItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItemById(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItemById(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItemsByCategory(arg0: string): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItemsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItemsByCategory(arg0);
            return result;
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubscription(): Promise<Subscription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubscription();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubscription();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderById(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderById(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderById(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderDelivery(arg0: bigint): Promise<OrderDelivery | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderDelivery(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderDelivery(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeOrder(arg0: Array<OrderItem>, arg1: number, arg2: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async subscribeToPlan(arg0: SubscriptionPlan): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeToPlan(to_candid_SubscriptionPlan_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeToPlan(to_candid_SubscriptionPlan_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async toggleAvailability(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAvailability(arg0);
            return result;
        }
    }
    async updateCoupon(arg0: Coupon): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCoupon(to_candid_Coupon_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCoupon(to_candid_Coupon_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDeliveryRider(arg0: DeliveryRider): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeliveryRider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeliveryRider(arg0);
            return result;
        }
    }
    async updateIngredient(arg0: IngredientItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIngredient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIngredient(arg0);
            return result;
        }
    }
    async updateMenuItem(arg0: MenuItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n40(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n40(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CouponDiscountType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CouponDiscountType): CouponDiscountType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Coupon_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Coupon): Coupon {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_OrderDelivery_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderDelivery): OrderDelivery {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionPlan_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionPlan): SubscriptionPlan {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuItem]): MenuItem | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Subscription]): Subscription | null {
    return value.length === 0 ? null : from_candid_Subscription_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderDelivery]): OrderDelivery | null {
    return value.length === 0 ? null : from_candid_OrderDelivery_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignedAt: [] | [bigint];
    riderId: [] | [bigint];
    orderId: bigint;
}): {
    assignedAt?: bigint;
    riderId?: bigint;
    orderId: bigint;
} {
    return {
        assignedAt: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.assignedAt)),
        riderId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.riderId)),
        orderId: value.orderId
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    userId: Principal;
    createdAt: bigint;
    totalAmount: number;
    notes: [] | [string];
    items: Array<_OrderItem>;
}): {
    id: bigint;
    status: OrderStatus;
    userId: Principal;
    createdAt: bigint;
    totalAmount: number;
    notes?: string;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n20(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        createdAt: value.createdAt,
        totalAmount: value.totalAmount,
        notes: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.notes)),
        items: value.items
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _SubscriptionStatus;
    userId: Principal;
    plan: _SubscriptionPlan;
    startDate: bigint;
}): {
    id: bigint;
    status: SubscriptionStatus;
    userId: Principal;
    plan: SubscriptionPlan;
    startDate: bigint;
} {
    return {
        id: value.id,
        status: from_candid_SubscriptionStatus_n26(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        plan: from_candid_SubscriptionPlan_n28(_uploadFile, _downloadFile, value.plan),
        startDate: value.startDate
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    active: boolean;
    discountValue: number;
    expiryDate: bigint;
    code: string;
    discountType: _CouponDiscountType;
    usedCount: bigint;
    usageLimit: bigint;
}): {
    id: bigint;
    active: boolean;
    discountValue: number;
    expiryDate: bigint;
    code: string;
    discountType: CouponDiscountType;
    usedCount: bigint;
    usageLimit: bigint;
} {
    return {
        id: value.id,
        active: value.active,
        discountValue: value.discountValue,
        expiryDate: value.expiryDate,
        code: value.code,
        discountType: from_candid_CouponDiscountType_n10(_uploadFile, _downloadFile, value.discountType),
        usedCount: value.usedCount,
        usageLimit: value.usageLimit
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fixed: null;
} | {
    percentage: null;
}): CouponDiscountType {
    return "fixed" in value ? CouponDiscountType.fixed : "percentage" in value ? CouponDiscountType.percentage : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "preparing" in value ? OrderStatus.preparing : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "outForDelivery" in value ? OrderStatus.outForDelivery : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
}): SubscriptionStatus {
    return "active" in value ? SubscriptionStatus.active : "cancelled" in value ? SubscriptionStatus.cancelled : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthly: null;
} | {
    weekly: null;
}): SubscriptionPlan {
    return "monthly" in value ? SubscriptionPlan.monthly : "weekly" in value ? SubscriptionPlan.weekly : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderDelivery>): Array<OrderDelivery> {
    return value.map((x)=>from_candid_OrderDelivery_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subscription>): Array<Subscription> {
    return value.map((x)=>from_candid_Subscription_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Coupon>): Array<Coupon> {
    return value.map((x)=>from_candid_Coupon_n8(_uploadFile, _downloadFile, x));
}
function to_candid_CouponDiscountType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CouponDiscountType): _CouponDiscountType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Coupon_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Coupon): _Coupon {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionPlan_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionPlan): _SubscriptionPlan {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    active: boolean;
    discountValue: number;
    expiryDate: bigint;
    code: string;
    discountType: CouponDiscountType;
    usedCount: bigint;
    usageLimit: bigint;
}): {
    id: bigint;
    active: boolean;
    discountValue: number;
    expiryDate: bigint;
    code: string;
    discountType: _CouponDiscountType;
    usedCount: bigint;
    usageLimit: bigint;
} {
    return {
        id: value.id,
        active: value.active,
        discountValue: value.discountValue,
        expiryDate: value.expiryDate,
        code: value.code,
        discountType: to_candid_CouponDiscountType_n3(_uploadFile, _downloadFile, value.discountType),
        usedCount: value.usedCount,
        usageLimit: value.usageLimit
    };
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionPlan): {
    monthly: null;
} | {
    weekly: null;
} {
    return value == SubscriptionPlan.monthly ? {
        monthly: null
    } : value == SubscriptionPlan.weekly ? {
        weekly: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CouponDiscountType): {
    fixed: null;
} | {
    percentage: null;
} {
    return value == CouponDiscountType.fixed ? {
        fixed: null
    } : value == CouponDiscountType.percentage ? {
        percentage: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} {
    return value == OrderStatus.preparing ? {
        preparing: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.outForDelivery ? {
        outForDelivery: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
