/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AdminUserRecord {
    principal: Principal;
    profile: UserProfile;
}
export interface Coupon {
    id: bigint;
    active: boolean;
    discountValue: number;
    expiryDate: bigint;
    code: string;
    discountType: CouponDiscountType;
    usedCount: bigint;
    usageLimit: bigint;
}
export interface OrderItem {
    quantity: bigint;
    unitPrice: number;
    menuItemId: bigint;
}
export interface DashboardStats {
    totalRevenue: number;
    totalCustomers: bigint;
    activeSubscriptions: bigint;
    todayOrders: bigint;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    userId: Principal;
    createdAt: bigint;
    totalAmount: number;
    notes?: string;
    items: Array<OrderItem>;
}
export interface AppSettings {
    deliveryCharge: number;
    taxEnabled: boolean;
    gstNumber: string;
    businessName: string;
    businessAddress: string;
    whatsappNumber: string;
    freeDeliveryAbove: number;
    servicePincodes: Array<string>;
    taxPercentage: number;
}
export interface Subscription {
    id: bigint;
    status: SubscriptionStatus;
    endDate: bigint;
    userId: Principal;
    plan: SubscriptionPlan;
    remainingSalads: bigint;
    totalSalads: bigint;
    startDate: bigint;
}
export interface SaladIngredient {
    quantityRequired: bigint;
    ingredientId: bigint;
    saladId: bigint;
}
export interface MenuItem {
    id: bigint;
    calories: bigint;
    name: string;
    description: string;
    available: boolean;
    imageUrl?: string;
    category: string;
    price: number;
    protein: bigint;
}
export interface OrderDelivery {
    assignedAt?: bigint;
    riderId?: bigint;
    deliveryStatus?: string;
    orderId: bigint;
    riderName?: string;
}
export interface DeliveryRider {
    id: bigint;
    name: string;
    available: boolean;
    phone: string;
}
export interface IngredientItem {
    id: bigint;
    lowStockThreshold: bigint;
    name: string;
    unit: string;
    pricePerUnit: number;
    quantity: bigint;
}
export interface UserProfile {
    age?: bigint;
    bmi?: number;
    weight?: number;
    height?: number;
    dietaryPreferences?: string;
    name: string;
    mobileNumber: string;
    email?: string;
    dietaryRestrictions?: string;
    address?: string;
    idealWeight?: number;
    gender?: string;
    dailyCalories?: bigint;
}
export enum CouponDiscountType {
    fixed = "fixed",
    percentage = "percentage"
}
export enum OrderStatus {
    preparing = "preparing",
    cancelled = "cancelled",
    pending = "pending",
    outForDelivery = "outForDelivery",
    delivered = "delivered",
    confirmed = "confirmed"
}
export enum SubscriptionPlan {
    monthly = "monthly",
    weekly = "weekly"
}
export enum SubscriptionStatus {
    active = "active",
    cancelled = "cancelled",
    paused = "paused"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCoupon(coupon: Coupon): Promise<void>;
    addDeliveryRider(rider: DeliveryRider): Promise<void>;
    addIngredient(item: IngredientItem): Promise<void>;
    addMenuItem(item: MenuItem): Promise<void>;
    adminCancelSubscription(id: bigint): Promise<void>;
    adminCreateSubscription(userId: Principal, plan: SubscriptionPlan, totalSalads: bigint, remainingSalads: bigint, startDate: bigint, endDate: bigint, status: SubscriptionStatus): Promise<bigint>;
    adminCreateUser(user: Principal, profile: UserProfile): Promise<void>;
    adminDeleteSubscription(id: bigint): Promise<void>;
    adminDeleteUser(user: Principal): Promise<void>;
    adminExtendSubscription(id: bigint, newEndDate: bigint, additionalSalads: bigint): Promise<void>;
    adminGetAllUsers(): Promise<Array<AdminUserRecord>>;
    adminPauseSubscription(id: bigint): Promise<void>;
    adminUpdateSubscription(id: bigint, plan: SubscriptionPlan, totalSalads: bigint, remainingSalads: bigint, startDate: bigint, endDate: bigint, status: SubscriptionStatus): Promise<void>;
    adminUpdateUser(user: Principal, profile: UserProfile): Promise<void>;
    applyCoupon(code: string): Promise<number>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRiderToOrder(orderId: bigint, riderId: bigint): Promise<void>;
    cancelSubscription(): Promise<void>;
    createOrUpdateProfile(profile: UserProfile): Promise<void>;
    deleteCoupon(id: bigint): Promise<void>;
    deleteIngredient(id: bigint): Promise<void>;
    deleteMenuItem(id: bigint): Promise<void>;
    getActiveCoupons(): Promise<Array<Coupon>>;
    getAllCoupons(): Promise<Array<Coupon>>;
    getAllDeliveryRiders(): Promise<Array<DeliveryRider>>;
    getAllIngredients(): Promise<Array<IngredientItem>>;
    getAllMenuItems(): Promise<Array<MenuItem>>;
    getAllOrderDeliveries(): Promise<Array<OrderDelivery>>;
    getAllOrders(): Promise<Array<Order>>;
    getAllSaladIngredients(): Promise<Array<{
        saladId: bigint;
        ingredients: Array<SaladIngredient>;
    }>>;
    getAllSubscriptions(): Promise<Array<Subscription>>;
    getAppSettings(): Promise<AppSettings>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getMenuItemById(id: bigint): Promise<MenuItem | null>;
    getMenuItemsByCategory(category: string): Promise<Array<MenuItem>>;
    getMyOrders(): Promise<Array<Order>>;
    getMyProfile(): Promise<UserProfile | null>;
    getMySubscription(): Promise<Subscription | null>;
    getOrderById(orderId: bigint): Promise<Order | null>;
    getOrderDelivery(orderId: bigint): Promise<OrderDelivery | null>;
    getSaladIngredients(saladId: bigint): Promise<Array<SaladIngredient>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    placeOrder(items: Array<OrderItem>, totalAmount: number, notes: string | null): Promise<bigint>;
    saveAppSettings(settings: AppSettings): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setSaladIngredients(saladId: bigint, ingredientList: Array<SaladIngredient>): Promise<void>;
    subscribeToPlan(plan: SubscriptionPlan): Promise<bigint>;
    toggleAvailability(id: bigint): Promise<void>;
    updateCoupon(coupon: Coupon): Promise<void>;
    updateDeliveryRider(rider: DeliveryRider): Promise<void>;
    updateDeliveryStatus(orderId: bigint, deliveryStatus: string): Promise<void>;
    updateIngredient(item: IngredientItem): Promise<void>;
    updateMenuItem(item: MenuItem): Promise<void>;
    updateOrderStatus(orderId: bigint, status: OrderStatus): Promise<void>;
}
import type { AdminUserRecord as _AdminUserRecord, Coupon as _Coupon, CouponDiscountType as _CouponDiscountType, MenuItem as _MenuItem, Order as _Order, OrderDelivery as _OrderDelivery, OrderItem as _OrderItem, OrderStatus as _OrderStatus, Subscription as _Subscription, SubscriptionPlan as _SubscriptionPlan, SubscriptionStatus as _SubscriptionStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCoupon(arg0: Coupon): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoupon(to_candid_Coupon_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoupon(to_candid_Coupon_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addDeliveryRider(arg0: DeliveryRider): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDeliveryRider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDeliveryRider(arg0);
            return result;
        }
    }
    async addIngredient(arg0: IngredientItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addIngredient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIngredient(arg0);
            return result;
        }
    }
    async addMenuItem(arg0: MenuItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(to_candid_MenuItem_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(to_candid_MenuItem_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adminCancelSubscription(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCancelSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCancelSubscription(arg0);
            return result;
        }
    }
    async adminCreateSubscription(arg0: Principal, arg1: SubscriptionPlan, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: SubscriptionStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateSubscription(arg0, to_candid_SubscriptionPlan_n7(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, to_candid_SubscriptionStatus_n9(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateSubscription(arg0, to_candid_SubscriptionPlan_n7(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, to_candid_SubscriptionStatus_n9(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async adminCreateUser(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateUser(arg0, to_candid_UserProfile_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateUser(arg0, to_candid_UserProfile_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminDeleteSubscription(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteSubscription(arg0);
            return result;
        }
    }
    async adminDeleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteUser(arg0);
            return result;
        }
    }
    async adminExtendSubscription(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminExtendSubscription(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminExtendSubscription(arg0, arg1, arg2);
            return result;
        }
    }
    async adminGetAllUsers(): Promise<Array<AdminUserRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUsers();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUsers();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminPauseSubscription(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminPauseSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminPauseSubscription(arg0);
            return result;
        }
    }
    async adminUpdateSubscription(arg0: bigint, arg1: SubscriptionPlan, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: SubscriptionStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateSubscription(arg0, to_candid_SubscriptionPlan_n7(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, to_candid_SubscriptionStatus_n9(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateSubscription(arg0, to_candid_SubscriptionPlan_n7(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, to_candid_SubscriptionStatus_n9(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async adminUpdateUser(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateUser(arg0, to_candid_UserProfile_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateUser(arg0, to_candid_UserProfile_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async applyCoupon(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.applyCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyCoupon(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRiderToOrder(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRiderToOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRiderToOrder(arg0, arg1);
            return result;
        }
    }
    async cancelSubscription(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelSubscription();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelSubscription();
            return result;
        }
    }
    async createOrUpdateProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(to_candid_UserProfile_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(to_candid_UserProfile_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCoupon(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoupon(arg0);
            return result;
        }
    }
    async deleteIngredient(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIngredient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIngredient(arg0);
            return result;
        }
    }
    async deleteMenuItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0);
            return result;
        }
    }
    async getActiveCoupons(): Promise<Array<Coupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveCoupons();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveCoupons();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCoupons(): Promise<Array<Coupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCoupons();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCoupons();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDeliveryRiders(): Promise<Array<DeliveryRider>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeliveryRiders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeliveryRiders();
            return result;
        }
    }
    async getAllIngredients(): Promise<Array<IngredientItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIngredients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIngredients();
            return result;
        }
    }
    async getAllMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMenuItems();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMenuItems();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrderDeliveries(): Promise<Array<OrderDelivery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrderDeliveries();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrderDeliveries();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSaladIngredients(): Promise<Array<{
        saladId: bigint;
        ingredients: Array<SaladIngredient>;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSaladIngredients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSaladIngredients();
            return result;
        }
    }
    async getAllSubscriptions(): Promise<Array<Subscription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubscriptions();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubscriptions();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppSettings(): Promise<AppSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppSettings();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getMenuItemById(arg0: bigint): Promise<MenuItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItemById(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItemById(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItemsByCategory(arg0: string): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItemsByCategory(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItemsByCategory(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubscription(): Promise<Subscription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubscription();
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubscription();
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderById(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderById(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderById(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderDelivery(arg0: bigint): Promise<OrderDelivery | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderDelivery(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderDelivery(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSaladIngredients(arg0: bigint): Promise<Array<SaladIngredient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSaladIngredients(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSaladIngredients(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeOrder(arg0: Array<OrderItem>, arg1: number, arg2: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, to_candid_opt_n54(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, to_candid_opt_n54(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async saveAppSettings(arg0: AppSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAppSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAppSettings(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setSaladIngredients(arg0: bigint, arg1: Array<SaladIngredient>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSaladIngredients(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSaladIngredients(arg0, arg1);
            return result;
        }
    }
    async subscribeToPlan(arg0: SubscriptionPlan): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeToPlan(to_candid_SubscriptionPlan_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeToPlan(to_candid_SubscriptionPlan_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async toggleAvailability(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAvailability(arg0);
            return result;
        }
    }
    async updateCoupon(arg0: Coupon): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCoupon(to_candid_Coupon_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCoupon(to_candid_Coupon_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDeliveryRider(arg0: DeliveryRider): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeliveryRider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeliveryRider(arg0);
            return result;
        }
    }
    async updateDeliveryStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeliveryStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeliveryStatus(arg0, arg1);
            return result;
        }
    }
    async updateIngredient(arg0: IngredientItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIngredient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIngredient(arg0);
            return result;
        }
    }
    async updateMenuItem(arg0: MenuItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(to_candid_MenuItem_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(to_candid_MenuItem_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n55(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n55(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AdminUserRecord_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminUserRecord): AdminUserRecord {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_CouponDiscountType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CouponDiscountType): CouponDiscountType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Coupon_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Coupon): Coupon {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_MenuItem_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): MenuItem {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_OrderDelivery_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderDelivery): OrderDelivery {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionPlan_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionPlan): SubscriptionPlan {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuItem]): MenuItem | null {
    return value.length === 0 ? null : from_candid_MenuItem_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Subscription]): Subscription | null {
    return value.length === 0 ? null : from_candid_Subscription_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderDelivery]): OrderDelivery | null {
    return value.length === 0 ? null : from_candid_OrderDelivery_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    profile: _UserProfile;
}): {
    principal: Principal;
    profile: UserProfile;
} {
    return {
        principal: value.principal,
        profile: from_candid_UserProfile_n16(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: [] | [bigint];
    bmi: [] | [number];
    weight: [] | [number];
    height: [] | [number];
    dietaryPreferences: [] | [string];
    name: string;
    mobileNumber: string;
    email: [] | [string];
    dietaryRestrictions: [] | [string];
    address: [] | [string];
    idealWeight: [] | [number];
    gender: [] | [string];
    dailyCalories: [] | [bigint];
}): {
    age?: bigint;
    bmi?: number;
    weight?: number;
    height?: number;
    dietaryPreferences?: string;
    name: string;
    mobileNumber: string;
    email?: string;
    dietaryRestrictions?: string;
    address?: string;
    idealWeight?: number;
    gender?: string;
    dailyCalories?: bigint;
} {
    return {
        age: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.age)),
        bmi: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.bmi)),
        weight: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.weight)),
        height: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.height)),
        dietaryPreferences: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.dietaryPreferences)),
        name: value.name,
        mobileNumber: value.mobileNumber,
        email: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.email)),
        dietaryRestrictions: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.dietaryRestrictions)),
        address: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.address)),
        idealWeight: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.idealWeight)),
        gender: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.gender)),
        dailyCalories: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.dailyCalories))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    active: boolean;
    discountValue: number;
    expiryDate: bigint;
    code: string;
    discountType: _CouponDiscountType;
    usedCount: bigint;
    usageLimit: bigint;
}): {
    id: bigint;
    active: boolean;
    discountValue: number;
    expiryDate: bigint;
    code: string;
    discountType: CouponDiscountType;
    usedCount: bigint;
    usageLimit: bigint;
} {
    return {
        id: value.id,
        active: value.active,
        discountValue: value.discountValue,
        expiryDate: value.expiryDate,
        code: value.code,
        discountType: from_candid_CouponDiscountType_n26(_uploadFile, _downloadFile, value.discountType),
        usedCount: value.usedCount,
        usageLimit: value.usageLimit
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    calories: bigint;
    name: string;
    description: string;
    available: boolean;
    imageUrl: [] | [string];
    category: string;
    price: number;
    protein: bigint;
}): {
    id: bigint;
    calories: bigint;
    name: string;
    description: string;
    available: boolean;
    imageUrl?: string;
    category: string;
    price: number;
    protein: bigint;
} {
    return {
        id: value.id,
        calories: value.calories,
        name: value.name,
        description: value.description,
        available: value.available,
        imageUrl: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.imageUrl)),
        category: value.category,
        price: value.price,
        protein: value.protein
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignedAt: [] | [bigint];
    riderId: [] | [bigint];
    deliveryStatus: [] | [string];
    orderId: bigint;
    riderName: [] | [string];
}): {
    assignedAt?: bigint;
    riderId?: bigint;
    deliveryStatus?: string;
    orderId: bigint;
    riderName?: string;
} {
    return {
        assignedAt: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.assignedAt)),
        riderId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.riderId)),
        deliveryStatus: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.deliveryStatus)),
        orderId: value.orderId,
        riderName: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.riderName))
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    userId: Principal;
    createdAt: bigint;
    totalAmount: number;
    notes: [] | [string];
    items: Array<_OrderItem>;
}): {
    id: bigint;
    status: OrderStatus;
    userId: Principal;
    createdAt: bigint;
    totalAmount: number;
    notes?: string;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n38(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        createdAt: value.createdAt,
        totalAmount: value.totalAmount,
        notes: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.notes)),
        items: value.items
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _SubscriptionStatus;
    endDate: bigint;
    userId: Principal;
    plan: _SubscriptionPlan;
    remainingSalads: bigint;
    totalSalads: bigint;
    startDate: bigint;
}): {
    id: bigint;
    status: SubscriptionStatus;
    endDate: bigint;
    userId: Principal;
    plan: SubscriptionPlan;
    remainingSalads: bigint;
    totalSalads: bigint;
    startDate: bigint;
} {
    return {
        id: value.id,
        status: from_candid_SubscriptionStatus_n43(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        userId: value.userId,
        plan: from_candid_SubscriptionPlan_n45(_uploadFile, _downloadFile, value.plan),
        remainingSalads: value.remainingSalads,
        totalSalads: value.totalSalads,
        startDate: value.startDate
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fixed: null;
} | {
    percentage: null;
}): CouponDiscountType {
    return "fixed" in value ? CouponDiscountType.fixed : "percentage" in value ? CouponDiscountType.percentage : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "preparing" in value ? OrderStatus.preparing : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "outForDelivery" in value ? OrderStatus.outForDelivery : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    paused: null;
}): SubscriptionStatus {
    return "active" in value ? SubscriptionStatus.active : "cancelled" in value ? SubscriptionStatus.cancelled : "paused" in value ? SubscriptionStatus.paused : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthly: null;
} | {
    weekly: null;
}): SubscriptionPlan {
    return "monthly" in value ? SubscriptionPlan.monthly : "weekly" in value ? SubscriptionPlan.weekly : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminUserRecord>): Array<AdminUserRecord> {
    return value.map((x)=>from_candid_AdminUserRecord_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Coupon>): Array<Coupon> {
    return value.map((x)=>from_candid_Coupon_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Array<MenuItem> {
    return value.map((x)=>from_candid_MenuItem_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderDelivery>): Array<OrderDelivery> {
    return value.map((x)=>from_candid_OrderDelivery_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subscription>): Array<Subscription> {
    return value.map((x)=>from_candid_Subscription_n41(_uploadFile, _downloadFile, x));
}
function to_candid_CouponDiscountType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CouponDiscountType): _CouponDiscountType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Coupon_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Coupon): _Coupon {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_MenuItem_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuItem): _MenuItem {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionPlan_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionPlan): _SubscriptionPlan {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): _SubscriptionStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age?: bigint;
    bmi?: number;
    weight?: number;
    height?: number;
    dietaryPreferences?: string;
    name: string;
    mobileNumber: string;
    email?: string;
    dietaryRestrictions?: string;
    address?: string;
    idealWeight?: number;
    gender?: string;
    dailyCalories?: bigint;
}): {
    age: [] | [bigint];
    bmi: [] | [number];
    weight: [] | [number];
    height: [] | [number];
    dietaryPreferences: [] | [string];
    name: string;
    mobileNumber: string;
    email: [] | [string];
    dietaryRestrictions: [] | [string];
    address: [] | [string];
    idealWeight: [] | [number];
    gender: [] | [string];
    dailyCalories: [] | [bigint];
} {
    return {
        age: value.age ? candid_some(value.age) : candid_none(),
        bmi: value.bmi ? candid_some(value.bmi) : candid_none(),
        weight: value.weight ? candid_some(value.weight) : candid_none(),
        height: value.height ? candid_some(value.height) : candid_none(),
        dietaryPreferences: value.dietaryPreferences ? candid_some(value.dietaryPreferences) : candid_none(),
        name: value.name,
        mobileNumber: value.mobileNumber,
        email: value.email ? candid_some(value.email) : candid_none(),
        dietaryRestrictions: value.dietaryRestrictions ? candid_some(value.dietaryRestrictions) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        idealWeight: value.idealWeight ? candid_some(value.idealWeight) : candid_none(),
        gender: value.gender ? candid_some(value.gender) : candid_none(),
        dailyCalories: value.dailyCalories ? candid_some(value.dailyCalories) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    active: boolean;
    discountValue: number;
    expiryDate: bigint;
    code: string;
    discountType: CouponDiscountType;
    usedCount: bigint;
    usageLimit: bigint;
}): {
    id: bigint;
    active: boolean;
    discountValue: number;
    expiryDate: bigint;
    code: string;
    discountType: _CouponDiscountType;
    usedCount: bigint;
    usageLimit: bigint;
} {
    return {
        id: value.id,
        active: value.active,
        discountValue: value.discountValue,
        expiryDate: value.expiryDate,
        code: value.code,
        discountType: to_candid_CouponDiscountType_n3(_uploadFile, _downloadFile, value.discountType),
        usedCount: value.usedCount,
        usageLimit: value.usageLimit
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    calories: bigint;
    name: string;
    description: string;
    available: boolean;
    imageUrl?: string;
    category: string;
    price: number;
    protein: bigint;
}): {
    id: bigint;
    calories: bigint;
    name: string;
    description: string;
    available: boolean;
    imageUrl: [] | [string];
    category: string;
    price: number;
    protein: bigint;
} {
    return {
        id: value.id,
        calories: value.calories,
        name: value.name,
        description: value.description,
        available: value.available,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        category: value.category,
        price: value.price,
        protein: value.protein
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): {
    active: null;
} | {
    cancelled: null;
} | {
    paused: null;
} {
    return value == SubscriptionStatus.active ? {
        active: null
    } : value == SubscriptionStatus.cancelled ? {
        cancelled: null
    } : value == SubscriptionStatus.paused ? {
        paused: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CouponDiscountType): {
    fixed: null;
} | {
    percentage: null;
} {
    return value == CouponDiscountType.fixed ? {
        fixed: null
    } : value == CouponDiscountType.percentage ? {
        percentage: null
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} {
    return value == OrderStatus.preparing ? {
        preparing: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.outForDelivery ? {
        outForDelivery: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionPlan): {
    monthly: null;
} | {
    weekly: null;
} {
    return value == SubscriptionPlan.monthly ? {
        monthly: null
    } : value == SubscriptionPlan.weekly ? {
        weekly: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
